# Site Settings
title: Scratch Pad
tagline: Mark Delcambre's Random Projects

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
