title:  Scratch Pad
tagline:  A blog for some random projects
author:
  name: "Mark Delcambre"
  twitter:  "charkbot"

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/mdelcambre'}
- {icon: 'twitter', link: 'https://twitter.com/charkbot'}
- {icon: 'instagram', link: 'https://instagram.com/charkbot'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/mdelcambre/'}
- {icon: 'envelope', link: 'mailto:mark@delcambre.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
